# Polar-orbiting observation stream for temporal JEPA.

METOP_ABC_AVHRR_IASI:
  type: obs
  stream_id: 20
  filenames: ['observations-ea-ofb-0001-2007-2021-metop-a-iasi-radiances-v1.zarr', 'observations-ea-ofb-0001-2013-2023-metop-b-iasi-radiances-v1.zarr', 'observations-ea-ofb-0001-2019-2023-metop-c-iasi-radiances-v1.zarr']
  geoinfo_channels: ['cos_local_time', 'sin_local_time', 'cos_julian_day', 'sin_julian_day', 'noise_time']
  forcing: True
  loss_weight: 1.0
  token_size: 512
  tokenize_spacetime: False
  embed:
    net: transformer
    num_tokens: 1
    num_heads: 2
    dim_embed: 256
    num_blocks: 2
  embed_target_coords:
    net: linear
    dim_embed: 256
  target_readout:
    num_layers: 2
    num_heads: 4
  pred_head:
    ens_size: 1
    num_layers: 1
